// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsjIGOS41CZD8lIt3pKfTlt9BasC7yALs',
    appId: '1:868852610341:android:1d1a84484b007c0e2f96cc',
    messagingSenderId: '868852610341',
    projectId: 'geo-hr',
    databaseURL: 'https://geo-hr-default-rtdb.firebaseio.com',
    storageBucket: 'geo-hr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9u5Sp7thlxHa9rgV2mU7TT6frI4rA04',
    appId: '1:868852610341:ios:7199cc0057ccc4c62f96cc',
    messagingSenderId: '868852610341',
    projectId: 'geo-hr',
    databaseURL: 'https://geo-hr-default-rtdb.firebaseio.com',
    storageBucket: 'geo-hr.appspot.com',
    iosClientId: '868852610341-keeb10ds43ocpp413dnvu00a1eemd6og.apps.googleusercontent.com',
    iosBundleId: 'com.example.geoAttendanceSystemHr',
  );
}
